import type { Metadata } from "next";
import { Manrope, Outfit, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const poppins = Manrope({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Campus Eats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
